-- Users are provisioned from Keycloak on first login; id is the token's "sub" claim.
create table users (
    id           uuid         primary key,
    username     varchar(100) not null unique,
    email        varchar(255),
    display_name varchar(200),
    role         varchar(20)  not null,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null
);

create table award_event (
    id          bigint generated by default as identity primary key,
    name        varchar(200)  not null,
    description varchar(4000),
    deadline    timestamp with time zone not null,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null
);

create table proposal (
    id             bigint generated by default as identity primary key,
    award_event_id bigint        not null references award_event (id),
    leader_id      uuid          not null references users (id),
    title          varchar(200)  not null,
    description    varchar(4000),
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null
);

create index idx_proposal_award_event on proposal (award_event_id);
create index idx_proposal_leader on proposal (leader_id);

create table proposal_member (
    id          bigint generated by default as identity primary key,
    proposal_id bigint not null references proposal (id) on delete cascade,
    user_id     uuid   not null references users (id),
    created_at  timestamp with time zone not null,
    constraint uk_proposal_member unique (proposal_id, user_id)
);

create index idx_proposal_member_user on proposal_member (user_id);

create table proposal_file (
    id                bigint generated by default as identity primary key,
    proposal_id       bigint        not null references proposal (id) on delete cascade,
    original_filename varchar(255)  not null,
    content_type      varchar(255),
    size_bytes        bigint        not null,
    storage_key       varchar(255)  not null unique,
    uploaded_by       uuid          not null references users (id),
    uploaded_at       timestamp with time zone not null
);

create index idx_proposal_file_proposal on proposal_file (proposal_id);
