-- One row per audited operation (API request or unattributed entity change).
create table audit_log (
    id            uuid primary key,
    occurred_at   timestamp(6) with time zone not null,
    actor_id      varchar(255),
    actor_name    varchar(255),
    action        varchar(100) not null,
    outcome       varchar(20)  not null,
    error_type    varchar(255),
    http_method   varchar(10),
    route         varchar(500),
    path          varchar(2000),
    client_ip     varchar(100),
    request_id    varchar(100),
    duration_ms   bigint
);

create index idx_audit_log_actor on audit_log (actor_id, occurred_at);

-- One row per changed entity field, committed as part of the operation above.
-- This is where affected resources come from: an operation may touch any number of entities.
create table audit_log_change (
    id           bigint generated by default as identity primary key,
    audit_log_id uuid         not null references audit_log (id) on delete cascade,
    entity_type  varchar(100) not null,
    entity_id    varchar(255) not null,
    operation    varchar(10)  not null,
    field_name   varchar(100) not null,
    old_value    varchar(4000),
    new_value    varchar(4000)
);

create index idx_audit_log_change_log on audit_log_change (audit_log_id);
create index idx_audit_log_change_entity on audit_log_change (entity_type, entity_id);
